import { useAppDispatch } from '@/store';
import { useEffect } from 'react';
import { fetchMovies } from '@/store/slices/movie';
import { Hero, MoviesForYou } from '@/section/home';
import { Footer, Navbar } from '@/components/navigation';
import Head from 'next/head';

export default function Home() {
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(fetchMovies())
  }, [])

  return (
    <>
      <Head>
        <title>Vader | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div className="flex flex-col min-h-screen">
        <Navbar />
        <div className="flex-auto">
          <div className='bg-[#1B1F32]'>
            <Hero learnMore={true} />
            <MoviesForYou heading={"Movies for you"} />
          </div>
        </div>
        <Footer />
      </div>
    </>
  )
}
